[package]
name = "matrix-seshat"
version = "2.3.3"
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk>"]
license = "Apache-2.0"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
bundled-sqlcipher = ["seshat/bundled-sqlcipher"]

# We are pinning the exact version of neon since it has a track record of
# introducing breaking changes in patch releases.

[dependencies]
fs_extra = "1.3.0"
serde_json = "1.0.61"
neon-serde3 = "0.10.0"
uuid = "1.3.0"
seshat = { path = "../", version = "2.3.3" }

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-4"]
