matrix:
  allow_failures:
    - os: windows
  include:
    - os: linux
      language: rust
      env:
        - TRAVIS_NODE_VERSION="12"
    - os: osx
      language: rust
      env:
        - TRAVIS_NODE_VERSION="12"
    - os: windows
      language: rust
      env:
        - TRAVIS_NODE_VERSION="12"

cache: cargo

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    export NVS_HOME=$ProgramData/nvs;
    git clone --single-branch https://github.com/jasongin/nvs $NVS_HOME;
    source $NVS_HOME/nvs.sh;
    nvs --version;
    nvs add $TRAVIS_NODE_VERSION && nvs use $TRAVIS_NODE_VERSION;
    else
    nvm install $TRAVIS_NODE_VERSION;
    nvm use ${TRAVIS_NODE_VERSION};
    fi
  - node -v
  - npm -v
  - npm i -g yarn@latest neon-cli@latest
  - npm install

script:
  - cargo test
  - cd seshat-node
  - yarn install
  - yarn test
  - yarn lint
