[package]
name = "seshat-node"
version = "2.1.0"
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk>"]
license = "Apache-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "seshat_node"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
neon = "0.4.0"
fs_extra = "1.1.0"
serde_json = "1.0.53"
neon-serde = "0.4.0"
uuid = { version = "0.8.1" }
seshat = { version = "2.1.0", path = "../../" }
