[package]
name = "seshat-node"
version = "0.1.0"
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk>"]
license = "Apache-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "seshat_node"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.3.*"

[dependencies]
neon = "0.3"
fs_extra = "1.1.0"
serde_json = "1.0"
r2d2 = "0.8"
r2d2_sqlite = "0.12"
neon-serde = "0.2.0"
seshat = { git = "https://github.com/matrix-org/seshat/", rev = "6c7af53" }
