[package]
name = "seshat-node"
version = "1.2.0"
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk>"]
license = "Apache-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "seshat_node"
crate-type = ["cdylib"]

# We pin the neon versions since neon introduced a breaking change in a minor
# version bump. While this is unlikely to occur again let us pin the versions
# for a while.

[build-dependencies]
neon-build = "=0.3.3"

[dependencies]
neon = "=0.3.3"
fs_extra = "1.1.0"
serde_json = "1.0.44"
neon-serde = "=0.3.0"
seshat = { version = "1.2.0" }
